name: Deploy to Production

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: pnpm --filter @repo/db exec npx prisma generate --schema=packages/prisma/schema.prisma

      - name: Build apps
        run: pnpm run build

      - name: Upload build to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 13.51.200.131
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "apps/web/.next/*"
          target: "~/week-25-ci-cd-next-app/apps/web/.next"

      - name: Restart app on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.51.200.131
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd week-25-ci-cd-next-app
            pm2 restart all || pm2 start "pnpm start"