name: Deployment to staging

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  redeploy-everything:
    runs-on: ubuntu-latest 
    steps: 
    - run: | 
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/ssh_key
        chmod 600 ~/ssh_key
        mkdir -p ~/.ssh
        ssh-keyscan -H 56.228.41.167 >> ~/.ssh/known_hosts
        ssh -i ~/ssh_key ubuntu@13.51.200.131 -t "
          export NVM_DIR=\"$HOME/.nvm\";
          [ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\";
          [ -s \"$NVM_DIR/bash_completion\" ] && . \"$NVM_DIR/bash_completion\";
          nvm use node;
          export PATH=\$PATH:/home/ubuntu/.nvm/versions/node/v22.21.0/bin;
          cd week-25-ci-cd-next-app/;
          git pull origin production;
          npm install -g pnpm pm2;
          pnpm install;
          pnpm run build;
          pm2 restart fe-server;
          pm2 restart http-server;
          pm2 restart ws-server;
        "