name: Deploy to Production

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install & Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm run build

      - name: Upload build to EC2 and restart
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 13.51.200.131
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "~/week-25-ci-cd-next-app/dist"

      - name: Restart app on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.51.200.131
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd week-25-ci-cd-next-app
            pm2 restart all || pm2 start pnpm --name fe-server -- start