name: Deployment to staging

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  redeploy-everything:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 13.51.200.131
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            cd week-25-ci-cd-next-app/
            git pull origin production
            npm install -g pnpm pm2
            pnpm install
            pnpm run build
            pm2 restart fe-server
            pm2 restart http-server
            pm2 restart ws-server