name: Deployment to staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  redeploy-everything:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/ssh_key
        chmod 600 ~/ssh_key
        mkdir -p ~/.ssh
        ssh-keyscan -H 56.228.41.167 >> ~/.ssh/known_hosts
        ssh -i ~/ssh_key ubuntu@56.228.41.167 -t "
          cd week-25-ci-cd-next-app/;
          git pull origin main;
          npm install -g pnpm pm2;
          pnpm install;
          pnpm run build;
          pm2 restart fe-server;
          pm2 restart http-server;
          pm2 restart ws-server;
        "